# Generated by Django 3.2.7 on 2021-09-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="residents",
            field=models.ManyToManyField(
                blank=True, related_name="activities", to="activities.Resident"
            ),
        ),
    ]
