# Generated by Django 3.2.7 on 2021-09-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_activity_residents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
