# Generated by Django 3.2.7 on 2021-09-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_alter_activity_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
